# This is a basic workflow to help you get started with Actions

name: CI
# Set permissions
permissions:
  contents: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      #Install Pandoc
      - name: Setup pandoc
        # You may pin to the exact commit or the version.
        # uses: nikeee/setup-pandoc@65d1fee002ea71e0d2a1c39bfa392c4e7ceba563
        uses: nikeee/setup-pandoc@v1
        with:
          # Exact version of pandoc to use. You can find available versions here: https://github.com/jgm/pandoc/releases

          pandoc-version: latest
          # This option defaults to the workflow scoped GitHub Token.It is used to not hit the rate limit while determining the 'latest' version of pandoc.If you need to specify a different token to be used, you can use this option. We expect that normal users typically don't have to do that.

          token: ${{ github.token }}
          
      # Runs a set of commands using the runners shell
      - name: Deploy pages
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

        
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          make build
          ls html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: html # The folder the action should deploy.
      

          
